---
- include_vars:
    file: forecast.yml
    name: forecast

- name: Set environment variables
  lineinfile:
    dest: /etc/environment
    line: FORECAST_KEY={{ forecast.key }}
    notify:
      - Restart server
      - Wait for server to restart

- name: Install SenseHAT examples
  git: repo=https://github.com/bennuttall/sense-hat-examples.git
       dest=/src/bennuttall/sense-hat-examples
       accept_hostkey=yes

- name: Install foxy1982 repository
  git: repo=https://github.com/foxy1982/RaspberryPi.git
       dest=/src/foxy1982/RaspberryPi
       accept_hostkey=yes

- name: Install weather-hat service script
  copy: src=weather-hat.service
        dest=/lib/systemd/system/weather-hat.service

- name: Start weather-hat service
  service: name=weather-hat
           state=started
