---
- name: Install tools
  apt: name="{{item}}" state=present
  with_items:
    - git
    - leafpad
  become: yes

- name: Install SenseHAT examples
  git: repo=git@github.com:bennuttall/sense-hat-examples.git
       dest=/src/sense-hat-examples
       accept_hostkey=yes
