---

- name: Ansible Playbook for configuring brand new Raspberry Pi with weather hat

  hosts: pi
  tasks:
   - name: updates a server
     apt: update_cache=yes
  roles:
    - weather-hat
    - webserver
  remote_user: pi
  become: yes
